GET http://localhost:8080/api/players

###

GET http://localhost:8080/api/players/7af085cd-a7f1-4be9-a18a-3f6e98c9a7a9

###

POST http://localhost:8080/api/players
Content-Type: application/json

{
  "fullName": "Andrzej",
  "age": 20,
  "height": 1.85,
  "weight": 80,
  "position": "Striker",
  "value": 828282,
  "nationality": "Poland",
  "teamName": "First team"
}

###

DELETE http://localhost:8080/api/players/5faf4c79-f538-4c8f-90b5-91be74ecde3d

###

PUT http://localhost:8080/api/players/3c00e180-c97d-4642-aa97-7e2c4c97c788
Content-Type: application/json

{
  "fullName": "Andrzej Dodany",
  "age": 40,
  "position": "Midfielder",
  "value": 444222,
  "nationality": "Poland"
}

###

GET http://localhost:8080/api/teams

###

GET http://localhost:8080/api/teams/NewTeam

###

POST http://localhost:8080/api/teams
Content-Type: application/json

{
  "name": "NewTeam",
  "budget": 842932232
}

###

DELETE http://localhost:8080/api/teams/First team

###

PUT http://localhost:8080/api/teams/NewTeam
Content-Type: application/json

{
  "budget": 99999999
}

###

GET http://localhost:8080/api/teams/First team/players

###

GET http://localhost:8080/api/teams/First team/players/6be14229-f5f6-48b1-a6aa-f4fafa24e443

###

POST http://localhost:8080/api/teams/First team/players
Content-Type: application/json

{
  "fullName": "Andrzej",
  "age": 20,
  "height": 1.85,
  "weight": 80,
  "position": "Striker",
  "value": 828282.0,
  "nationality": "Poland",
  "teamName": "First team"
}

###

DELETE http://localhost:8080/api/teams/First team/players/3f1adabb-2db5-4ab7-9c6a-d10639f44c62

###

PUT http://localhost:8080/api/teams/First team/players/3fd18e59-29a7-4a67-921d-659f470fac6d
Content-Type: application/json

{
  "fullName": "Andrzej Jakis",
  "age": 40,
  "position": "Midfielder",
  "value": 444222,
  "nationality": "Poland"
}