GET http://localhost:8081/api/teams

###

GET http://localhost:8081/api/teams/First team

###

POST http://localhost:8081/api/teams
Content-Type: application/json

{
  "name": "NewTeam",
  "budget": 842932232
}

###

DELETE http://localhost:8081/api/teams/NewTeam

###

PUT http://localhost:8081/api/teams/NewTeam
Content-Type: application/json

{
  "budget": 99999999
}
